### ISSUE TITLE
DIfferences between arxiv v1 and CVF version

### ISSUE THREAD

**Issue by MiZhenxing** [cmusatyalab/mega-nerf#15]
Hi, thanks for your great work. I found that the Table 2. Scalable training in CVF version (arxiv v2) are different from arxiv v1. Could you give some details about your techniques to improve the mega-nerf performance? Thank you very much.

**Comment by hturki** [comment]
Hey - a big difference between the first and second drafts in Arxiv is that we ended up using poses refined with PixSFM in the latter, which improved overall quality but quite a bit. Hope that helps!

**Comment by MiZhenxing** [comment]
Thank you very much for your quick response!
