### ISSUE TITLE
how to see results after training?

### ISSUE THREAD

**Issue by Furenchampion** [cmusatyalab/mega-nerf#17]
thank you for your excellent work! 
I have a question. I use dataset building and after training i cannot see the results of whole scene.
Is there a .mp4 or some images exist to show the training result?
Besides: I notice in render_images.py ,which requires input including pose.txt/intrinsics.txt/embeddings.txt. how can i get these ?

**Comment by hturki** [comment]
Hi @Furenchampion - after merging the submodules as mentioned in the README, the eval script will output renderings of the validation set to tensorboard. 

I mainly used render_images.py to generate things like the demo videos, but the pose.txt/intrinsics.txt/embeddings.txt file format is pretty simple (one c2w matrix in the same coordinate system as the dataset/one intrinsics matrix/one embedding index per line)

**Comment by Furenchampion** [comment]
Thanks!
I still have a question , what is embeddings.txt file consist of?
I guess It related to metadata.image_index ? But Im not sure . 
I create a embedding.txt consist of number 1 to 1920(since I use dataset building-pixsfm,1920 is the train set amount)
error occurs:

File "/meganerf/mega-nerf/mega_nerf/runner.py", line 570, in render_image
    image_indices = img_index * torch.ones(rays.shape[0], device=rays.device) \
RuntimeError: The size of tensor a (1920) must match the size of tensor b (15925248) at non-singleton dimension 0

I know 15925248 is the height of the image multiply the width , but Im confused what happened here
Could you explain?
Thank you!

**Comment by Furenchampion** [comment]
Thanks!
I still have a question , what is embeddings.txt file consist of?
I guess It related to metadata.image_index ? But Im not sure .
I create a embedding.txt consist of number 1 to 1920(since I use dataset building-pixsfm,1920 is the train set amount)
error occurs:

File "/meganerf/mega-nerf/mega_nerf/runner.py", line 570, in render_image
image_indices = metadata.image_index* torch.ones(rays.shape[0], device=rays.device)
RuntimeError: The size of tensor a (1920) must match the size of tensor b (15925248) at non-singleton dimension 0

I know 15925248 is the height of the image multiply the width , but Im confused what happened here
Could you explain?
Thank you!

**Comment by hturki** [comment]
Mega-NeRF uses a per-image embedding vector, and so ends up with # training images embedding vectors after training. So at inference time you need to just specify which you wish to use (a number between 0 - 1919 in your case since we're using zero-indexing).

You want pose.txt/intrinsics.txt/embeddings.txt to all have the same number of lines, where each line corresponds to a rendered frame.

**Comment by zyqz97** [comment]
Hello, I can generate the rendered images according to the given train/val poses. But how can I set up the fly-through trajectory to create the video (https://github.com/cmusatyalab/mega-nerf#demo)?  The fly-through trajectory of the demo seems different from the given train/val poses. Are there any tools?

**Comment by hturki** [comment]
I unfortunately don't have a great answer here - for some of the flythroughs I generated paths via trial-and-error, and for other ones I plotted out the trajectories using instant-ngp's (https://github.com/NVlabs/instant-ngp) viewer and then converting the coordinate trajectories to mega-nerf's format. I don't have any ready-made code to provide alas.
