### ISSUE TITLE
How are the chunk files in MegaNeRF generated?

### ISSUE THREAD

**Issue by ZZy129326999** [cmusatyalab/mega-nerf#19]
Dear the experts, how are the chunk files in MegaNeRF generated? Thank you very much!

**Comment by ZZy129326999** [comment]
I have solved it, it is directly set but not created to finish it.

**Comment by xiaoxiaolu1111** [comment]
How did you create it?No metadata.pt file.

**Comment by ZZy129326999** [comment]
> How did you create it?No metadata.pt file.

Please directly make a new chunk directory in your project.

**Comment by hyunJIN7** [comment]
> > How did you create it?No metadata.pt file.
> 
> Please directly make a new chunk directory in your project.

Hi. Can you tell me how to create a chunk directory in more detail?

**Comment by Shrinkink** [comment]
您好，我已经在像目录下创建了chunk目录，但提示我还是找不到metadata.pt文件，请问您遇到过此类问题吗，或者我猜想是代码中的某些问题导致的？谢谢！
