### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by joonho3020** [cmusatyalab/mega-nerf#2]
I read the paper and its great work. However, I would like one clarification on the evaluation section. For inference (rendering), did you guys use 8 V100 GPUs like in the training or just a single GPU?
Thanks!

**Comment by hturki** [comment]
Inferencing was measured against a single GPU. Just to be explicit and avoid confusion, the "Multi-GPU evaluation" part in the README just distributes images across GPUs to speed up validation (ie: each validation is done against a single GPU)
