### ISSUE TITLE
Training speed almost irrelevant to the size of dataset

### ISSUE THREAD

**Issue by h8c2** [cmusatyalab/mega-nerf#21]
I have trained the building dataset with 1000+ images and a sample of 50 images of the dataset.  I trained on 4 3090 GPUs and it took almost 40 hours.
However, the train time of the small dataset was almost as same as big one. I was wondering how to speed up this process.
Thanks a lot.

**Comment by h8c2** [comment]
got it

**Comment by evyy1234** [comment]
> got it

can you tell me how to speed up it ?thanks

**Comment by h8c2** [comment]
train_iterations++ after getting a batch of rays from data loader instead of going through the entire dataset. Hence you should manually set the number of train iterations according to the dataset size(also your resolution and overlap rate of images) to get a result of the same metric.
