### ISSUE TITLE
chunk arguments questions

### ISSUE THREAD

**Issue by hyunJIN7** [cmusatyalab/mega-nerf#22]
Hi, Thank you for the great work.
I'm trying to train meganerf with Mill19 Building data.
Could I ask you some questions about the chunk file?
I read [issue#1](https://github.com/cmusatyalab/mega-nerf/issues/1). But I don't know how to use chuck file yet.
Like [@novasky0709](https://github.com/novasky0709) in issue#1,
I created an empty directory first and set it to the `--chunk_paths`.
I encountered the same error with [@novasky0709](https://github.com/novasky0709):
`FileNotFoundError: [Errno 2] No such file or directory: 'output/mill19/building-pixsfm/metadata.pt' `
Is it right to set the empty folder as `chucks_path`?
How do I fix metadata.pt file errors?

Thanks,
Hyunjin Kim.

**Comment by hturki** [comment]
As mentioned in https://github.com/cmusatyalab/mega-nerf/issues/1#issuecomment-1079388085 - the directory to chunks_path should not initially exist. Can you delete the directory and try again?

**Comment by hyunJIN7** [comment]
Thank you for the guidance. 
It worked well when I deleted the chunk directory and ran it without it.
