### ISSUE TITLE
Support to train on blockNeRF's dataset to make comparison

### ISSUE THREAD

**Issue by HrsPythonix** [cmusatyalab/mega-nerf#23]
Great work done! I find there's another work named [BlockNeRF](https://waymo.com/research/block-nerf/) that also concentrate on NeRF in large scene, I wonder if you have made a comparison between your work and theirs.

Since BlockNeRF haven't released their code but their dataset, I think it's only possible now to train MegaNeRF on BlockNeRF's data. Can you share how to do that?

**Comment by hturki** [comment]
BlockNeRF and Mega-NeRF are concurrent bodies of work that share many similarities. Two noteworthy differences are that they use MipNeRF as the base architecture while we use something similar to the original NeRF formulation, and how we assign training pixels/rays to submodules.

Assuming that the BlockNeRF dataset provides images and camera poses then it should be pretty straightforward to evaluate Mega-NeRF following the instructions for custom data in the README: https://github.com/cmusatyalab/mega-nerf#custom-data
