### ISSUE TITLE
Module import error 

### ISSUE THREAD

**Issue by sumanttyagi** [cmusatyalab/mega-nerf#24]
facing below issue in nb . But i am able to run the command "from mega_nerf.misc_utils import main_tqdm, main_print" in cell. any soln ?
![image](https://user-images.githubusercontent.com/63983323/180975212-190ccc63-6c48-47bd-9946-9e6d8556d771.png)

**Comment by wuzirui** [comment]
try adding the mega-nerf folder to system path?
``` python
import sys
sys.path.append('/mnt/sdb1/sumant/act_nerf/nbs/mega-nerf-main/')
from mega_nerf.misc_utils import main_tqdm, main_print
...
```

**Comment by sumanttyagi** [comment]
still it does not fix my issue.

> try adding the mega-nerf folder to system path?
> 
> ```python
> import sys
> sys.path.append('/mnt/sdb1/sumant/act_nerf/nbs/mega-nerf-main/')
> from mega_nerf.misc_utils import main_tqdm, main_print
> ...
> ```

the solution is not working.
i am able to run this line "from mega_nerf.misc_utils import main_tqdm, main_print" separately in the cell. but when i try running the script "!python /mnt/sdb1/sumant/act_nerf/nbs/mega-nerf-main/scripts/create_cluster_masks.py --config configs/mega-nerf/building.yml --dataset_path '/mnt/sdb1/sumant/act_nerf/building-pixsfm' --output'/mnt/sdb1/sumant/act_nerf/building-pixsfm/mask' --grid_dim 2 4"..shows error for modulenotfounderror as below:
![image](https://user-images.githubusercontent.com/63983323/180982349-026958a8-c2fb-4bac-a3d6-9a266696bf16.png)

**Comment by hjxwhy** [comment]
You can try `export PYTHONPATH=$PWD/mega-nerf`

**Comment by sumanttyagi** [comment]
> You can try `export PYTHONPATH=$PWD/mega-nerf`

thanks working fine in terminal , :)
can you suggest any solution for jupyter nb also  ?
