### ISSUE TITLE
CUDA out of memory when creating mask

### ISSUE THREAD

**Issue by weidezhang** [cmusatyalab/mega-nerf#29]
Hi I used the quad6 dataset and set the grid_dim to 10, 10

However, I get the following cuda_outof_memory error: 
 RuntimeError: CUDA out of memory. Tried to allocate 18.31 GiB (GPU 0; 23.70 GiB total capacity; 18.57 GiB already allocated; 3.13 GiB free; 18.58 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I'm using 3090 with 8 cards. I dont understand why it caused the out of memory issue. 

Weide

**Comment by sjtuytc** [comment]
You should have a larger GPU or reduce the number of rays. However, I found the process is very very slow.

**Comment by sumanttyagi** [comment]
decrease the grid dim to size  2 4 or 2 2

**Comment by hturki** [comment]
the ray_chunk_size and dist_chunk_size options also would reduce memory requirements. You can also try playing with the ray_samples but that might impact accuracy. Otherwise the pregenerated masks should be available with links in the README
