### ISSUE TITLE
What is --ckpt_prefix？

### ISSUE THREAD

**Issue by chl2** [cmusatyalab/mega-nerf#31]
Thanks for the code, I have some problems when reproducing
1. What is --ckpt_prefix ${EXP_PREFIX} in the Merge step?
2. In the Evaluation step, what is the --exp_name  $EXP_NAME? Is it the sub-model related files generated when training each submodule? Can we directly use the output model you provided for direct evaluation?
Thank you very much for any reply.

**Comment by sumanttyagi** [comment]
2. Yes this is the submodule , mega-nerf have feature sub module i guess you should use merge to get all the view points

**Comment by hturki** [comment]
1. assuming your individual submodules were trained with a checkpoint directory such as "/foo/submodule-0", /foo/submodule-1", etc, you'd pass in "/foo/submodule-" as the prefix and the merging script will iterate through all of the trained submodule directories.

https://github.com/cmusatyalab/mega-nerf/blob/main/scripts/merge_submodules.py#L34

**Comment by Kikihqq** [comment]
> 1. assuming your individual submodules were trained with a checkpoint directory such as "/foo/submodule-0", /foo/submodule-1", etc, you'd pass in "/foo/submodule-" as the prefix and the merging script will iterate through all of the trained submodule directories.
> 
> https://github.com/cmusatyalab/mega-nerf/blob/main/scripts/merge_submodules.py#L34
I find it has some errors in this step:

My input checkpoint directory is  "--ckpt_prefix logs/exp/ex-", but the root seems error:
```
Traceback (most recent call last):
  File "/home/paper/Desktop/meganerf/scripts/merge_submodules.py", line 113, in <module>
    main(_get_merge_opts())
  File "/home/paper/anaconda3/envs/mega-nerf/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/paper/Desktop/meganerf/scripts/merge_submodules.py", line 51, in main
    version_dirs = sorted([int(x.name) for x in list(centroid_path.iterdir())], reverse=True)
  File "/home/paper/Desktop/meganerf/scripts/merge_submodules.py", line 51, in <listcomp>
    version_dirs = sorted([int(x.name) for x in list(centroid_path.iterdir())], reverse=True)
ValueError: invalid literal for int() with base 10: 'hparams.txt'
```
what the meaning of `version_dirs` ?

![image](https://user-images.githubusercontent.com/78300031/230908477-63d33dbb-881c-41e8-a39d-3824d72cb357.png)

Could you please help me solve this problem? Thanks a lot.

**Comment by SSXXSSXX** [comment]
> y input checkpoint directory is "--ckpt_prefix logs/exp/ex-", but the root seems error
"I've encountered the same issue. Have you managed to solve it?"
