### ISSUE TITLE
what parameters we can use do to speed up the training for custom dataset

### ISSUE THREAD

**Issue by sumanttyagi** [cmusatyalab/mega-nerf#32]
what are the parameters could be changed for training of the model more quickly ,want to use all the computational power without any resources left unused while training . 

What all parameters could be changed for the above statement while using the (1) custom dataset and (2) pre trained dataset  ?

**Comment by hturki** [comment]
some options would be to reduce the number of coarse samples and fine samples per ray, or reduce the capacity of the MLPs themselves (via the layer_dim and bg_layer_dim option)
