### ISSUE TITLE
how to set a scaling factor for custom dataset

### ISSUE THREAD

**Issue by sumanttyagi** [cmusatyalab/mega-nerf#33]
while changing from colmap to mega nerf format . There is need of these parameters --model_path --images_path --output_path --scale --num_val . However how to decide the --scale if i am providing colmap format ?

**Comment by hturki** [comment]
you want your coordinate bounds to generally fall between -1 and 1 for the positional encoding to behave properly

**Comment by sumanttyagi** [comment]
how should i select this value ?
