### ISSUE TITLE
colmap is generating multiple models 

### ISSUE THREAD

**Issue by sumanttyagi** [cmusatyalab/mega-nerf#34]
@hturki  how to use this script https://github.com/cmusatyalab/mega-nerf/blob/main/scripts/colmap_to_mega_nerf.py if i only want to use the output from colmap , as colmap is generating multiple models in which different images and points is being used .
![image](https://user-images.githubusercontent.com/63983323/184017818-64505342-3b1e-437d-a48e-3873ca5ba3c8.png)
 
which one to be used as there are 3 sets of cameras, images, points3D which one to pick ?

thanks in advance

**Comment by sumanttyagi** [comment]
do we need to merge these model and then feed to the script as provided ?

**Comment by hturki** [comment]
if COLMAP is generating multiple models, then that usually means that it's not finding enough matches to connect all of your images into a single model. Their README has some suggestions (https://colmap.github.io/faq.html#merge-disconnected-models) but in general I'd recommend adding more potential matches per image if possible
