### ISSUE TITLE
pixsfm cameras of Campus dataset

### ISSUE THREAD

**Issue by MiZhenxing** [cmusatyalab/mega-nerf#36]
Hi, seems the camera parameter link of Campus has broken (https://storage.cmusatyalab.org/mega-nerf-data/campus-pixsfm.tgz). Could you please update the link so we could fully test on the datasets? Thank you very much.

**Comment by jaharkes** [comment]
Not sure where that link is from but there is no `campus-pixsfm.tgz` dataset.

I can see the following files,

- `campus-pixsfm-8.pt`
- `campus-pixsfm-grid-8.tgz`
- `campus.tgz`

I don't know which one you need, looking at the naming of the other datasets it may be that `campus-pixsfm.tgz` has not been uploaded (yet?).

**Comment by MiZhenxing** [comment]
@jaharkes Hi, thank you for your response. The link is from the README.md
https://github.com/cmusatyalab/mega-nerf/blob/76d8d76b66d70f8a0819defc0cef4fb9aa251672/README.md?plain=1#L66
Similar to other dataset, we need campus-pixsfm.tgz for better camera parameters. But the link seems broken. Would you mind to reupload the this dataset? Thank you very much!

**Comment by zyqz97** [comment]
I have the same question about 'the link'.  Could you help me?  Thank you very much!   #28

**Comment by hturki** [comment]
hey folks - the link should work now - sorry for the delay
