### ISSUE TITLE
forward-facing dataset

### ISSUE THREAD

**Issue by Harperrrr111** [cmusatyalab/mega-nerf#37]
Hi, thanks for the excellent work.

I want to test the code on a relatively large-scale forward-facing dataset. How to change the code, particularly how to produce the centroids?  My understanding is that the parameter ray_altitude_range no longer needs. But I cannot get reasonable cluster mask.

**Comment by hturki** [comment]
you can probably specifying skip the ray_altitude_range parameter by using the --no_ellipse_bounds option. I personally haven't tested mega-nerf with forward-facing scenes. If you want to use NDC coordinates I guess you could apply the clustering on the non forward-facing dimensions but you might need to change other things in the codebase to properly handle NDC

**Comment by Harperrrr111** [comment]
Thanks for your answers. I will try.

**Comment by IaroslavS** [comment]
> Thanks for your answers. I will try.

Hi, did you manage to run Mega-NeRF on a forward facing dataset ?
