### ISSUE TITLE
Image.tvec is too large

### ISSUE THREAD

**Issue by leoShen917** [cmusatyalab/mega-nerf#39]
hi, @hturki .Congrats on your great work and thank you for releasing the code. I'm trying to use a custom dataset but I'm currently having some issues. I have successfully trained and inferred the eval. But there is a problem while extracting the octree. The translation vector of my dataset images is large，but the translation vectors of the datasets you provided are relatively small. This ended up causing my extraction of the octree to fail, the octree file size was only 2.89KB.
![57a5a635bce2f8f67e9a10bb282c6a9](https://user-images.githubusercontent.com/83259959/187332256-437edf3a-8150-4abe-8aa0-699607d2ee75.png)
Just to make sure I have no errors while processing the dataset
 1. run get_colmap_poses.py to get ref folder, pairs-sfm.txt, matches.h5. features.h5
 2. Use COLMAP's model_aligner utility (https://colmap.github.io/faq.html#geo-registration) to get geo-registered-model
 3. Use [mega-nerf/scripts/colmap_to_mega_nerf.py](https://github.com/cmusatyalab/mega-nerf/tree/main/scripts/colmap_to_mega_nerf.py) to convert from PixSFM/COLMAP output to the format Mega-NeRF expects.

Is there something I'm missing?Why is my translation vector so large.
Thanks and wish you all the best!

**Comment by leoShen917** [comment]
Is it true to convert GPS coordinates to ecef coordinates when registering in geo

**Comment by hturki** [comment]
I think either ENU or ECEF would work (I forget which I personally used) and then the idea is that the script will center the poses (https://github.com/cmusatyalab/mega-nerf/blob/main/scripts/colmap_to_mega_nerf.py#L357) and you want to specify a scale parameter than will normalize your poses to [-1, 1].

**Comment by pengzhao-life** [comment]
@leoShen917 Hi, for your step 2 Use COLMAP's model_aligner utility (https://colmap.github.io/faq.html#geo-registration) to get geo-registered-model, what arguments you used for '--ref_images_path' or '--database_path'? 
I got database reading error when I use '--database_path'. 
Thanks!

**Comment by leoShen917** [comment]
@pengzhao-life  I also got error when I use '--database_path', so I try to use '--ref_images_path' and it works. The ref file is something you need to build manually, in the format shown below.
![Snipaste_2022-09-23_18-48-04](https://user-images.githubusercontent.com/83259959/191945028-e1ab4e2c-2d36-4fcf-a914-5ab11d0ba4aa.png)
