### ISSUE TITLE
Question on campus, residence and sci-art sequences from UrbanScene3D dataset

### ISSUE THREAD

**Issue by santolina** [cmusatyalab/mega-nerf#4]
Thanks a lot for your great work!

I have a question on creating {campus, residence, sci-art} sequences from UrbanScene3D dataset.

Although I have downloaded UrbanScene3D dataset, it contains 3D model assets but none of raw RGB data.  
If you created those sequences via AirSim or UnrealEngine, could you share the scripts for that? 

Thanks!

**Comment by hturki** [comment]
Looking at https://github.com/whatseven/UrbanScene3D/issues/2#issuecomment-1097472292 I think you got it - these were all trained against the raw images and it seems like the dataset authors provide the links via email. Please let me know if you run into any issues after you get the raw images.

**Comment by santolina** [comment]
Thanks a lot for the clarification!
