### ISSUE TITLE
How about pinhole camera model

### ISSUE THREAD

**Issue by guijuzhejiang** [cmusatyalab/mega-nerf#40]
This works great, thank you for the open source. I am getting an error when trying to train on my own data. It seems that only the SIMPLE_RADIAL camera model is currently supported. If my camera model is pinhole, how can I modify it? Thanks in advance

**Comment by hturki** [comment]
Is pinhole not just simple_radial without radial distortion? Are you asking whether you can run the colmap/pixsfm phase without it trying to estimate radial distortion? If you look at the pixsfm/hloc/pycolmap codebase I believe that there is an option to set the camera model.
