### ISSUE TITLE
What is the meaning of the ray_altitude_range parameter?

### ISSUE THREAD

**Issue by guijuzhejiang** [cmusatyalab/mega-nerf#42]
What is the meaning of the ray_altitude_range parameter and how to set it correctly in custom dataset

**Comment by hturki** [comment]
The ray_altitude_range parameter is used to truncate ray sampling near ground level. You generally want to set the first value to be the height of the largest object in the foreground that you care about and the second to be close to ground level. Worse case you can disable this option by setting the --no_ellipse_bounds option
