### ISSUE TITLE
custom dataset: camera direction? 

### ISSUE THREAD

**Issue by pengzhao-life** [cmusatyalab/mega-nerf#43]
In gps matcher code as below, it seems that images are paired in line 124 based on the close gps (lat, lon, alt) and time.
[https://gist.github.com/hturki/5a76b1ee54b8cd23e34e075f8a8b87e0](url)

Are you using camera direction? For my custom data, at each gps location and with timestamp, multiple images were taken (say front view, right, back, and left view). I am not sure how to pair these images with different directions. Maybe estimate camera parameters using front view images only, and then convert the camera matrix for the left/right/back views? or estimate camera parameters using each view individually?

**Comment by hturki** [comment]
So in the gist I shared I'm just matching based on gps position and timestamp (not camera direction). Hope that helps!
