### ISSUE TITLE
Unable to download the pretrained models and datasets

### ISSUE THREAD

**Issue by Wei-Baldwin-Zeng** [cmusatyalab/mega-nerf#53]
Hi，great work！！！

The link for the pretrained models and the datasets seems broken. Could you please check them?

Thanks in advance.

**Comment by jaharkes** [comment]
Which were failing? I downloaded the rubble dataset and model with no problem earlier today.

**Comment by hturki** [comment]
im able to download them as well - please reopen if you're still running into issues
