### ISSUE TITLE
Obtaining UrbanScene3D Sci-Art, Campus and Residence images

### ISSUE THREAD

**Issue by logchan** [cmusatyalab/mega-nerf#55]
Related to #4.

As mentioned in the quoted issue (https://github.com/yilinliu77/UrbanScene3D/issues/2#issuecomment-1222194050), the authors no longer send out links via email, and the images should be found on their website.

Can you confirm that the images of Sci-Art is the same as the "Oblique Photography" images under "Real Scenes -> ARTSCI"?

Also, I can't find any raw image download links for Campus or Residence. Can you share the images?

Thanks.

**Comment by hturki** [comment]
I'm not exactly sure what corresponds to what anymore - from what I understand the layout of the UrbanScenes3D dataset might have changed since we used it in our paper. FWIW the metadata files we provide should have the names of the images we used!

**Comment by A-pril** [comment]
Now I mention the same question. Could you share your solution please?

**Comment by logchan** [comment]
> Now I mention the same question. Could you share your solution please?

Download UrbanScene3D-V1 from https://github.com/Linxius/UrbanScene3D#urbanscene3d-v1
