### ISSUE TITLE
Question about function get_ray_directions()

### ISSUE THREAD

**Issue by Liu-SD** [cmusatyalab/mega-nerf#57]
It's a nice work. But I have a question about the source code.
I found your code in ray_utls.py computes the ray directions with 
```
directions = torch.stack([(i - cx) / fx, -(j - cy) / fy, -torch.ones_like(i)], -1) 
```
Why the y and z are set to negative here?

**Comment by hturki** [comment]
this just sets the camera to opengl conventions. Most other NeRF repos adopt the same convention (although there are a few like https://github.com/Kai-46/nerfplusplus that keep OpenCV conventions)
