### ISSUE TITLE
Can't find mega-nerf

### ISSUE THREAD

**Issue by CUGXiaoBao** [cmusatyalab/mega-nerf#58]
What is the reason for this? The environment has already been configured.
![微信截图_20230324091838](https://user-images.githubusercontent.com/125234726/227400354-1707aa3c-5dfd-4392-85c3-a99de085b055.png)

**Comment by hturki** [comment]
can you try adding the mega-nerf directory to your PYTHONPATH environment variable?

**Comment by CUGXiaoBao** [comment]
Thank you very much for your answer. May I ask if the code must be replicated in a Linux system？

**Comment by hturki** [comment]
Unfortunately I've only tested this out on linux myself!

**Comment by CUGXiaoBao** [comment]
Thank you again for your reply.May I ask if my feedback on running this script is due to a system issue？
![Uploading QQ图片20230414105954.png…]()

**Comment by CUGXiaoBao** [comment]
Thank you again for your reply.May I ask if my feedback on running this script is due to a system issue？
![QQ图片20230414105954](https://user-images.githubusercontent.com/125234726/231933918-4388f04e-3b4e-4d39-977a-62d2ab6480fc.png)

**Comment by hturki** [comment]
That message isn't a systems issue - it's complaining that you're not specifying the ray_altitude_range parameter. If you're using one of the provided datasets the respective config file should have it - otherwise you will need to specify it for your own data.

**Comment by CUGXiaoBao** [comment]
Thank you very much for your answer.

**Comment by ZiyangYan** [comment]
> can you try adding the mega-nerf directory to your PYTHONPATH environment variable?

Hi, I also meet this problem in my ubuntu, how to deal with that, also add this directory to environment variable? It seems useless
![Screenshot from 2023-08-17 18-19-41](https://github.com/cmusatyalab/mega-nerf/assets/92861079/688d001c-b389-473b-abcf-9d3c98ad3e86)
![Screenshot from 2023-08-17 18-19-53](https://github.com/cmusatyalab/mega-nerf/assets/92861079/26a6d8b8-5827-4dd4-88bd-85f337c08419)
