### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by xingyi-li** [cmusatyalab/mega-nerf#6]
Congrats on your great work and thank you for releasing the code.
I am curious to train my custom dataset but get stuck in the dataset preparation process. I also notice that you mention in the paper: "We refine the initial GPS-derived camera poses in the Mill 19 and UrbanScene3D datasets and the estimates provided in the Quad 6k dataset using PixSFM." 

I have the following questions:
1. How are the initial camera poses derived from drone GPS and IMU sensors? How are the initial GPS-derived camera poses refined using PixSFM? Could you kindly provide the script that can generate camera poses?
2. Can the camera poses estimated by COLMAP work with Mega-NeRF? Or should also be refined by PixSFM?

Thanks in advance and really looking forward to your reply!
Xingyi

**Comment by hturki** [comment]
Hi @xingyi-li - thanks for the kind words. To answer your questions:

Re: the initial camera poses from the GPS and IMU - we're just using the GPS geotags in the image metadata. Often this is embedded in the JPEG metadata itself (for example https://developer.parrot.com/docs/pdraw/photo-metadata.html for ANAFI photos). We also used to use the camera orientation back when we were refining poses with a commercial solution, but didn't use it for our PixSFM poses. 

The PixSFM repo explains their process in detail but our usage of it is pretty straightforward - https://gist.github.com/hturki/b3ae2e020bcc2a08dbba402786f1fcd3 should give you an idea of how we refine the poses with it. The main deviation is that we used a custom GPS matcher which limits the image matching to only other images in its vicinity (https://gist.github.com/hturki/5a76b1ee54b8cd23e34e075f8a8b87e0) using the metadata found in the Mill19 and UrbanScene3D images. If your dataset is relatively small you might be able to get away with just using exhaustive matching.

Re: Using COLMAP instead of PixSFM - PixSFM uses COLMAP as part of their pipeline and does additional refinement before and after bundle adjustment, and they actually write the final result in COLMAP format. I just pushed a script that should convert COLMAP output (from PixSFM or just using COLMAP) at https://github.com/cmusatyalab/mega-nerf/blob/main/scripts/colmap_to_mega_nerf.py. As a word of caution, Mega-NeRF (and NeRF in general) is extremely sensitive to good camera poses, and we observed differences of over 6 PSNR when comparing PixSFM poses to that of a commercial photogrammetry software we initially used. So I'd strongly recommend using PixSFM if possible. And in either case, you will likely want to geo-register your result dataset using COLMAP's model_aligner utility (https://colmap.github.io/faq.html#geo-registration) so that Mega-NeRF's --ray_altitude_range parameter works properly. If you don't have geotags for your image you might be able to get away with manhattan world alignment (https://colmap.github.io/faq.html#manhattan-world-alignment) but it will probably not give you perfect bounds.

Hope that this helps!

**Comment by xingyi-li** [comment]
Hi @hturki, really appreciate your quick reply. I will try your suggestions as soon as possible and will report if I can successfully train my custom dataset. Temporarily closing this issue. 

Thanks again!
Xingyi

**Comment by xingyi-li** [comment]
Hi @hturki, just want to make sure that I understand you. I first summarize the total steps to obtain the refined camera poses Mega-NeRF expects:
1. Run the script at [https://gist.github.com/hturki/b3ae2e020bcc2a08dbba402786f1fcd3](https://gist.github.com/hturki/b3ae2e020bcc2a08dbba402786f1fcd3), where in line 38 of it, _pairs\_from\_gps_ actually corresponds to the script at [https://gist.github.com/hturki/5a76b1ee54b8cd23e34e075f8a8b87e0](https://gist.github.com/hturki/5a76b1ee54b8cd23e34e075f8a8b87e0). In _pairs\_from\_gps_, you derive the initial camera poses from the drones metadata. Then the initial camera poses are used to generate 'pairs-sfm.txt'. This limits the image matching to only other images in its vicinity. After this step, the refined camera poses using PixSFM have been obtained.
2. Use COLMAP's model_aligner utility ([https://colmap.github.io/faq.html#geo-registration](https://colmap.github.io/faq.html#geo-registration)) so that Mega-NeRF's --ray_altitude_range parameter works properly.
3. Use [mega-nerf/scripts/colmap_to_mega_nerf.py](https://github.com/cmusatyalab/mega-nerf/tree/main/scripts/colmap_to_mega_nerf.py) to convert from PixSFM/COLMAP output to the format Mega-NeRF expects.

Am I right?

I also have three questions:
1. It seems that in _pairs\_from\_gps_, you only make use of latitude, longitude, and altitude, without using things like roll, pitch, and yaw (or, orientation). Is that true?
2. As far as I am concerned, the so-called initial camera poses are only used to generate 'pairs-sfm.txt'. The camera poses that Mega-NeRF uses are actually estimated by PixSFM. Is that true?
3. Although you point out in README that the Scale factor maps from the real-world unit (ie: meters) to [-1, 1] range, I still get confused about how the value of the --scale parameter in [mega-nerf/scripts/colmap_to_mega_nerf.py](https://github.com/cmusatyalab/mega-nerf/tree/main/scripts/colmap_to_mega_nerf.py) is decided. Is it making camera_in_drb[:, 3] to be between [-1, 1]?

Thanks and wish you all the best!
Xingyi

**Comment by hturki** [comment]
Your summary of the needed steps seems right to me. To answer your other questions:

1. Yes, we're not making use of roll/pitch/yaw for our PixSFM poses (we explored using them when using a different commercial solution)
2. You're correct in that they're mainly used to minimize the image pairs that pixsfm/colmap have to evaluate (using exhaustive matching is prohibitive when your dataset is thousands of images). We also use these GPS readings to geo-reference the final poses (via colmap's model_aligner utility)
3. Yes, it's just a scaling factor to make sure all the poses fall within [-1, 1]. It should be pretty straightforward to modify the provided script to automatically determine a good scaling factor.

**Comment by xingyi-li** [comment]
Hi @hturki, I have two more questions:

1. I have followed https://github.com/cmusatyalab/mega-nerf/issues/6#issuecomment-1103654545 to generate the refined camera poses Mega-NeRF expects, but how --ray_altitude_range is decided?
2. As mentioned in https://github.com/cmusatyalab/mega-nerf/issues/14#issue-1253300130, I am also interested in generating videos through my camera trajectory :-)

Many thanks!

**Comment by hturki** [comment]
1. I don't have a very scientific way of doing this - sometimes I'd start off with a wide range, then quickly train a cheap model (10-20k iterations without using spatial partitioning), and then see what sort of range looks good in mega-nerf-viewer. In general you want ray altitude range to not extend too far below ground level while still containing your camera poses
2. Just commented on the ticket - would recommend giving https://github.com/NVlabs/instant-ngp a spin

**Comment by pengzhao-life** [comment]
@xingyi-li Have you successfully trained your custom dataset?

**Comment by sumanttyagi** [comment]
@pengzhao-life are you able to prepare the dataset as mentioned ?

**Comment by sumanttyagi** [comment]
@hturki https://gist.github.com/hturki/b3ae2e020bcc2a08dbba402786f1fcd3
explain how to use this and gps_matcher together. What i have understood is use install pixsfm run this script https://gist.github.com/hturki/b3ae2e020bcc2a08dbba402786f1fcd3 but i am facing some issue please check the comment on this link then use colmap to load the files generated from pixsfm apply aligner . Use this to colmap to mega_nerf direclty  use this for training ?

**Comment by weidezhang** [comment]
> Hi @hturki, I have two more questions:
> 
> 1. I have followed [Custom dataset #6 (comment)](https://github.com/cmusatyalab/mega-nerf/issues/6#issuecomment-1103654545) to generate the refined camera poses Mega-NeRF expects, but how --ray_altitude_range is decided?
> 2. As mentioned in [Demo camera trajectory #14 (comment)](https://github.com/cmusatyalab/mega-nerf/issues/14#issue-1253300130), I am also interested in generating videos through my camera trajectory :-)
> 
> Many thanks!

@xingyi-li have you figured out a way to estimate ray_altitude_range? what is this term represents ?

**Comment by pengzhao-life** [comment]
> Hi @hturki, just want to make sure that I understand you. I first summarize the total steps to obtain the refined camera poses Mega-NeRF expects:
> 
> 1. Run the script at https://gist.github.com/hturki/b3ae2e020bcc2a08dbba402786f1fcd3, where in line 38 of it, _pairs_from_gps_ actually corresponds to the script at https://gist.github.com/hturki/5a76b1ee54b8cd23e34e075f8a8b87e0. In _pairs_from_gps_, you derive the initial camera poses from the drones metadata. Then the initial camera poses are used to generate 'pairs-sfm.txt'. This limits the image matching to only other images in its vicinity. After this step, the refined camera poses using PixSFM have been obtained.
> 2. Use COLMAP's model_aligner utility (https://colmap.github.io/faq.html#geo-registration) so that Mega-NeRF's --ray_altitude_range parameter works properly.
> 3. Use [mega-nerf/scripts/colmap_to_mega_nerf.py](https://github.com/cmusatyalab/mega-nerf/tree/main/scripts/colmap_to_mega_nerf.py) to convert from PixSFM/COLMAP output to the format Mega-NeRF expects.
> 
> Am I right?
> 
> I also have three questions:
> 
> 1. It seems that in _pairs_from_gps_, you only make use of latitude, longitude, and altitude, without using things like roll, pitch, and yaw (or, orientation). Is that true?
> 2. As far as I am concerned, the so-called initial camera poses are only used to generate 'pairs-sfm.txt'. The camera poses that Mega-NeRF uses are actually estimated by PixSFM. Is that true?
> 3. Although you point out in README that the Scale factor maps from the real-world unit (ie: meters) to [-1, 1] range, I still get confused about how the value of the --scale parameter in [mega-nerf/scripts/colmap_to_mega_nerf.py](https://github.com/cmusatyalab/mega-nerf/tree/main/scripts/colmap_to_mega_nerf.py) is decided. Is it making camera_in_drb[:, 3] to be between [-1, 1]?
> 
> Thanks and wish you all the best! Xingyi

**Comment by pengzhao-life** [comment]
Hi, for step 2  "Use COLMAP's model_aligner utility", 
1) what 'alignment_type' did you use? 'ecef 'or 'enu' or something else, how do you decide it?
2) for '--ref_images_path' or '--database_path', I used the database.db file created from step 1 i.e. pixsfm reconstruction function. But 'colmap model_aligner' throws error 'SQLite error: colmap/src/base/databsase.cc: unable to open database file.

**Comment by chufall** [comment]
> Hi, for step 2 "Use COLMAP's model_aligner utility",
> 
> 1. what 'alignment_type' did you use? 'ecef 'or 'enu' or something else, how do you decide it?
> 2. for '--ref_images_path' or '--database_path', I used the database.db file created from step 1 i.e. pixsfm reconstruction function. But 'colmap model_aligner' throws error 'SQLite error: colmap/src/base/databsase.cc: unable to open database file.

@pengzhao-life  did you figure it out?

**Comment by Kikihqq** [comment]
> Hi @xingyi-li - thanks for the kind words. To answer your questions:
> 
> Re: the initial camera poses from the GPS and IMU - we're just using the GPS geotags in the image metadata. Often this is embedded in the JPEG metadata itself (for example https://developer.parrot.com/docs/pdraw/photo-metadata.html for ANAFI photos). We also used to use the camera orientation back when we were refining poses with a commercial solution, but didn't use it for our PixSFM poses.
> 
> The PixSFM repo explains their process in detail but our usage of it is pretty straightforward - https://gist.github.com/hturki/b3ae2e020bcc2a08dbba402786f1fcd3 should give you an idea of how we refine the poses with it. The main deviation is that we used a custom GPS matcher which limits the image matching to only other images in its vicinity (https://gist.github.com/hturki/5a76b1ee54b8cd23e34e075f8a8b87e0) using the metadata found in the Mill19 and UrbanScene3D images. If your dataset is relatively small you might be able to get away with just using exhaustive matching.
> 
> Re: Using COLMAP instead of PixSFM - PixSFM uses COLMAP as part of their pipeline and does additional refinement before and after bundle adjustment, and they actually write the final result in COLMAP format. I just pushed a script that should convert COLMAP output (from PixSFM or just using COLMAP) at https://github.com/cmusatyalab/mega-nerf/blob/main/scripts/colmap_to_mega_nerf.py. As a word of caution, Mega-NeRF (and NeRF in general) is extremely sensitive to good camera poses, and we observed differences of over 6 PSNR when comparing PixSFM poses to that of a commercial photogrammetry software we initially used. So I'd strongly recommend using PixSFM if possible. And in either case, you will likely want to geo-register your result dataset using COLMAP's model_aligner utility (https://colmap.github.io/faq.html#geo-registration) so that Mega-NeRF's --ray_altitude_range parameter works properly. If you don't have geotags for your image you might be able to get away with manhattan world alignment (https://colmap.github.io/faq.html#manhattan-world-alignment) but it will probably not give you perfect bounds.
> 
> Hope that this helps!

Hello, when i use the scripts to refine camera pose,but when run the `pairs_from_gps`, i got the error:

```
##### <Element '{http://www.w3.org/1999/02/22-rdf-syntax-ns#}Description' at 0x7feb8705b860>
Traceback (most recent call last):
  File "/home/paper/Desktop/meganerf/pixs.py", line 53, in <module>
    main(_get_opts())
  File "/home/paper/Desktop/meganerf/pixs.py", line 39, in main
    pairs_from_gps.main(sfm_pairs_path, images_path, references, 100, 4)
  File "/home/paper/Desktop/pixel-perfect-sfm/Hierarchical-Localization/hloc/pairs_from_gps.py", line 100, in main
    lat, long, alt, R, date = get_gps_pos(image_dir / image_id)
  File "/home/paper/Desktop/pixel-perfect-sfm/Hierarchical-Localization/hloc/pairs_from_gps.py", line 59, in get_gps_pos
    lat = float(root[0][0].get('{http://www.dji.com/drone-dji/1.0/}GpsLatitude'))
TypeError: float() argument must be a string or a number, not 'NoneType'
```
How can i fix it ? Thanks a lot.

**Comment by linhanwang** [comment]
> > Hi @xingyi-li - thanks for the kind words. To answer your questions:
> > Re: the initial camera poses from the GPS and IMU - we're just using the GPS geotags in the image metadata. Often this is embedded in the JPEG metadata itself (for example https://developer.parrot.com/docs/pdraw/photo-metadata.html for ANAFI photos). We also used to use the camera orientation back when we were refining poses with a commercial solution, but didn't use it for our PixSFM poses.
> > The PixSFM repo explains their process in detail but our usage of it is pretty straightforward - https://gist.github.com/hturki/b3ae2e020bcc2a08dbba402786f1fcd3 should give you an idea of how we refine the poses with it. The main deviation is that we used a custom GPS matcher which limits the image matching to only other images in its vicinity (https://gist.github.com/hturki/5a76b1ee54b8cd23e34e075f8a8b87e0) using the metadata found in the Mill19 and UrbanScene3D images. If your dataset is relatively small you might be able to get away with just using exhaustive matching.
> > Re: Using COLMAP instead of PixSFM - PixSFM uses COLMAP as part of their pipeline and does additional refinement before and after bundle adjustment, and they actually write the final result in COLMAP format. I just pushed a script that should convert COLMAP output (from PixSFM or just using COLMAP) at https://github.com/cmusatyalab/mega-nerf/blob/main/scripts/colmap_to_mega_nerf.py. As a word of caution, Mega-NeRF (and NeRF in general) is extremely sensitive to good camera poses, and we observed differences of over 6 PSNR when comparing PixSFM poses to that of a commercial photogrammetry software we initially used. So I'd strongly recommend using PixSFM if possible. And in either case, you will likely want to geo-register your result dataset using COLMAP's model_aligner utility (https://colmap.github.io/faq.html#geo-registration) so that Mega-NeRF's --ray_altitude_range parameter works properly. If you don't have geotags for your image you might be able to get away with manhattan world alignment (https://colmap.github.io/faq.html#manhattan-world-alignment) but it will probably not give you perfect bounds.
> > Hope that this helps!
> 
> Hello, when i use the scripts to refine camera pose,but when run the `pairs_from_gps`, i got the error:
> 
> ```
> ##### <Element '{http://www.w3.org/1999/02/22-rdf-syntax-ns#}Description' at 0x7feb8705b860>
> Traceback (most recent call last):
>   File "/home/paper/Desktop/meganerf/pixs.py", line 53, in <module>
>     main(_get_opts())
>   File "/home/paper/Desktop/meganerf/pixs.py", line 39, in main
>     pairs_from_gps.main(sfm_pairs_path, images_path, references, 100, 4)
>   File "/home/paper/Desktop/pixel-perfect-sfm/Hierarchical-Localization/hloc/pairs_from_gps.py", line 100, in main
>     lat, long, alt, R, date = get_gps_pos(image_dir / image_id)
>   File "/home/paper/Desktop/pixel-perfect-sfm/Hierarchical-Localization/hloc/pairs_from_gps.py", line 59, in get_gps_pos
>     lat = float(root[0][0].get('{http://www.dji.com/drone-dji/1.0/}GpsLatitude'))
> TypeError: float() argument must be a string or a number, not 'NoneType'
> ```
> 
> How can i fix it ? Thanks a lot.

I guess the images you use don't have meta data that the program can read.

**Comment by linhanwang** [comment]
> Hi @xingyi-li - thanks for the kind words. To answer your questions:
> 
> Re: the initial camera poses from the GPS and IMU - we're just using the GPS geotags in the image metadata. Often this is embedded in the JPEG metadata itself (for example https://developer.parrot.com/docs/pdraw/photo-metadata.html for ANAFI photos). We also used to use the camera orientation back when we were refining poses with a commercial solution, but didn't use it for our PixSFM poses.
> 
> The PixSFM repo explains their process in detail but our usage of it is pretty straightforward - https://gist.github.com/hturki/b3ae2e020bcc2a08dbba402786f1fcd3 should give you an idea of how we refine the poses with it. The main deviation is that we used a custom GPS matcher which limits the image matching to only other images in its vicinity (https://gist.github.com/hturki/5a76b1ee54b8cd23e34e075f8a8b87e0) using the metadata found in the Mill19 and UrbanScene3D images. If your dataset is relatively small you might be able to get away with just using exhaustive matching.
> 
> Re: Using COLMAP instead of PixSFM - PixSFM uses COLMAP as part of their pipeline and does additional refinement before and after bundle adjustment, and they actually write the final result in COLMAP format. I just pushed a script that should convert COLMAP output (from PixSFM or just using COLMAP) at https://github.com/cmusatyalab/mega-nerf/blob/main/scripts/colmap_to_mega_nerf.py. As a word of caution, Mega-NeRF (and NeRF in general) is extremely sensitive to good camera poses, and we observed differences of over 6 PSNR when comparing PixSFM poses to that of a commercial photogrammetry software we initially used. So I'd strongly recommend using PixSFM if possible. And in either case, you will likely want to geo-register your result dataset using COLMAP's model_aligner utility (https://colmap.github.io/faq.html#geo-registration) so that Mega-NeRF's --ray_altitude_range parameter works properly. If you don't have geotags for your image you might be able to get away with manhattan world alignment (https://colmap.github.io/faq.html#manhattan-world-alignment) but it will probably not give you perfect bounds.
> 
> Hope that this helps!

Hi, @hturki Thanks for your clear explanation. I wonder how did you finally get a whole model for a scene? I tried your code on Mill 9 dataset but I got multiple small models.
