### ISSUE TITLE
Question about running a demo

### ISSUE THREAD

**Issue by tonytonglt** [cmusatyalab/mega-nerf#7]
What a great work!
May I ask a few questions?
If I just want to run a demo, all I need to do is downloading one of the datasets and the pretrained model corresponding to the dataset, and running the **create_octree.py** to extract the octree and then see the result by the Mega-NeRF-Dynamic viewer, is that correct?
Moreover, what's the meaning of **--container_path** argument and what should I fill in to it?
Many thanks!

**Comment by hturki** [comment]
Hi - I think you largely got the steps. You can either use the pretrained model with the Mega-NeRF-Dynamic viewer after creating the initial octree or by just using conventional NeRF rendering via the ```render_images.py``` script in this repo. 

The ```--container_path``` should point towards the path of the merged model obtained after running ```merge_submodules.py``` or in your case it just just point towards the pretrained model.

**Comment by tonytonglt** [comment]
Hello, thanks for your reply!
I followed the steps and run the `create_octree.py`, but I got the following error:
```
python scripts/create_octree.py --config configs/mega-nerf/rubble.yaml --dataset_path /xxx/data/rubble-pixsfm/ --container_path /xxx/model/rubble-pixsfm-8.pt --output  /xxx/meganerf/
/xxx/anaconda3/envs/mega-nerf/lib/python3.9/site-packages/svox/helpers.py:371: UserWarning: CUDA extension svox.csrc could not be loaded! Operations will be slow.
Please do not import svox in the SVOX source directory.
  warn("CUDA extension svox.csrc could not be loaded! " +
Min and Max values: tensor([ 0.0609, -0.6882, -0.8277]) tensor([0.2409, 0.6882, 0.8277])
Center and radius before autoscale: [0.15085101127624512, 0.0, 0.0], [0.08999999612569809, 0.688200056552887, 0.8277291655540466]
Step 0: Auto scale
/home/xxx/anaconda3/envs/mega-nerf/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:09<00:00, 53.20it/s]
Center and radius after autoscale: [0.15085101127624512, 0.0, 0.0], [0.09160156548023224, 0.6874648928642273, 0.8264489769935608]
Data dim is 4
Creating tree
Step 1: Grid eval
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4096/4096 [00:39<00:00, 104.47it/s]
Calculating grid weights
Traceback (most recent call last):
  File "/home/xxx/mega-nerf/scripts/create_octree.py", line 295, in <module>
    main(_get_extraction_opts())
  File "/home/xxx/anaconda3/envs/mega-nerf/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/mega-nerf/scripts/create_octree.py", line 269, in main
    _step1(hparams, nerf, tree, poses, device)
  File "/home/xxx/mega-nerf/scripts/create_octree.py", line 169, in _step1
    grid_weights = _calculate_grid_weights(hparams, tree, poses, sigmas, reso)
  File "/home/xxx/mega-nerf/scripts/create_octree.py", line 110, in _calculate_grid_weights
    opts = _C.RenderOptions()
AttributeError: 'NoneType' object has no attribute 'RenderOptions'

```

Does it mean I did not install the `svox` well or any other thing goes wrong? I did install the `svox` and it showed 'successfully'.

By the way, how can I run `render_images.py`? There are --input, --output, --centroids_path arguments but I don't know what should I fill into them.

Thank you!

**Comment by menglongyue** [comment]
I have the questions too, in render_images.py, how to get poses.txt, intrinsics.txt and embeddings.txt

**Comment by hturki** [comment]
It looks like ```svox``` was built without CUDA. https://github.com/sxyu/svox/issues/4 might be helpful for sorting that part out.

Re: ```render_images.py```:
- ```input``` should be set to a folder containing ```poses.txt```, ```intrinsics.txt```, and ```embeddings.txt``` files. https://github.com/cmusatyalab/mega-nerf/blob/main/scripts/render_images.py#L40 provides some intuition on how these files are used (basically each is a text file containing a camera pose / camera intrinsics / embedding index per line)
- ```output``` will be where the rendered rgb / depth maps / centroid boundary estimates are written to disk
- ```centroids_path``` is a somewhat niche option used to generate the right-most panel of the demo images in this repo (overlaying the cell boundaries). You can either point it to a 'params.pt' file generated by the ```create_cluster_masks.py``` script or comment all the code relating to that option if you don't care about generating those overlays
