### ISSUE TITLE
can not found mega_nerf 

### ISSUE THREAD

**Issue by ZiyangYan** [cmusatyalab/mega-nerf#75]
when run "create_cluster_masks.py", it reported this problem, I tried it in two PC but still the same, the ubuntu version is 20.04LTS
<img width="378" alt="image_2023_08_18T10_00_52_239Z (1)" src="https://github.com/cmusatyalab/mega-nerf/assets/92861079/590a5661-bcfa-4725-821e-ca16195c43a7">
<img width="318" alt="image_2023_08_18T10_00_18_140Z (1)" src="https://github.com/cmusatyalab/mega-nerf/assets/92861079/d5736e2d-9196-416b-b94f-7e16b8a6501d">

**Comment by ZiyangYan** [comment]
in issue #58 , it mentioned the similar problem, but it is in windows, I also tried to add the mega-nerf directory to environment variable from pycharm, but it is useless

**Comment by IaroslavS** [comment]
> when run "create_cluster_masks.py", it reported this problem, I tried it in two PC but still the same, the ubuntu version is 20.04LTS <img alt="image_2023_08_18T10_00_52_239Z (1)" width="378" src="https://user-images.githubusercontent.com/92861079/261574499-590a5661-bcfa-4725-821e-ca16195c43a7.png"> <img alt="image_2023_08_18T10_00_18_140Z (1)" width="318" src="https://user-images.githubusercontent.com/92861079/261574572-d5736e2d-9196-416b-b94f-7e16b8a6501d.png">

```bash
export PYTHONPATH="${PYTHONPATH}:/media/zyan/sandiskSSD/NeRF_methods/mega-nerf
```

**Comment by ZiyangYan** [comment]
> > when run "create_cluster_masks.py", it reported this problem, I tried it in two PC but still the same, the ubuntu version is 20.04LTS <img alt="image_2023_08_18T10_00_52_239Z (1)" width="378" src="https://user-images.githubusercontent.com/92861079/261574499-590a5661-bcfa-4725-821e-ca16195c43a7.png"> <img alt="image_2023_08_18T10_00_18_140Z (1)" width="318" src="https://user-images.githubusercontent.com/92861079/261574572-d5736e2d-9196-416b-b94f-7e16b8a6501d.png">
> 
> ```shell
> export PYTHONPATH="${PYTHONPATH}:/media/zyan/sandiskSSD/NeRF_methods/mega-nerf
> ```

thanks

**Comment by ZiyangYan** [comment]
problem fix
