### ISSUE TITLE
Parameter problem about  "merge_submodules.py"

### ISSUE THREAD

**Issue by ZiyangYan** [cmusatyalab/mega-nerf#76]
In the last step of training you ask us to input
--config_file configs/mega-nerf/${DATASET_NAME}.yaml  
--ckpt_prefix ${EXP_PREFIX}- 
--centroid_path ${MASK_PATH}/params.pt 
--output $MERGED_O

**I just run "Train each submodule" once, and the checkpoints are saved in** "/media/zyan/sandiskSSD/datasets/Quad_6k/quad-pixsfm/experiment/10/models"
![Screenshot from 2023-08-24 12-11-23](https://github.com/cmusatyalab/mega-nerf/assets/92861079/55b80866-3b1b-46f5-80db-acc80ad2dbdf)

**In the second step, my parameter is** 
"mega_nerf/train.py --config_file configs/mega-nerf/quad.yaml --exp_name /media/zyan/sandiskSSD/datasets/Quad_6k/quad-pixsfm/experiment --dataset_path /media/zyan/sandiskSSD/datasets/Quad_6k/quad-pixsfm --chunk_paths /media/zyan/sandiskSSD/datasets/Quad_6k/quad-pixsfm/scratch --cluster_mask_path /media/zyan/sandiskSSD/datasets/Quad_6k/quad-pixsfm/mask --train_every 8"
**so I think the "--centroid_path" should be --cluster_mask_path/params.pt = media/zyan/sandiskSSD/datasets/Quad_6k/quad-pixsfm/mask/params.pt**
<img width="726" alt="1692872423535" src="https://github.com/cmusatyalab/mega-nerf/assets/92861079/dcab5a56-63b0-4696-8d59-d532c544c590">

**But when I open your code, I found you use the "ckpt_prefix" to check whether centroid is exist or not, what it means? Is it still meaningful for us to input centrold_path in the command?
And I always get error about can not find centrold_path like:**
<img width="471" alt="1692872596012" src="https://github.com/cmusatyalab/mega-nerf/assets/92861079/d3f5913e-a736-4df2-a457-47272eb7e5f1">

Traceback (most recent call last):
  File "/media/zyan/sandiskSSD/NeRF_methods/mega-nerf/mega-nerf-main/scripts/merge_submodules.py", line 102, in <module>
    main(_get_merge_opts())
  File "/media/zyan/sandiskSSD/anaconda3/envs/mega-nerf/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/media/zyan/sandiskSSD/NeRF_methods/mega-nerf/mega-nerf-main/scripts/merge_submodules.py", line 38, in main
    raise Exception('{} not found'.format(centroid_path))
Exception: /media/zyan/sandiskSSD/datasets/Quad_6k/quad-pixsfm/experiment/100 not found

**My input command is:**
python scripts/merge_submodules.py --config_file configs/mega-nerf/quad.yaml  --ckpt_prefix /media/zyan/sandiskSSD/datasets/Quad_6k/quad-pixsfm/experiment/10 --centroid_path /media/zyan/sandiskSSD/datasets/Quad_6k/quad-pixsfm/mask/params.pt --output /media/zyan/sandiskSSD/datasets/Quad_6k/quad-pixsfm/output

Can you describe more about the parameters for me? thank you

**Comment by IaroslavS** [comment]
I thins this [issue](https://github.com/cmusatyalab/mega-nerf/issues/31) is related this, but maybe not exactly

**Comment by IaroslavS** [comment]
I think this https://github.com/cmusatyalab/mega-nerf/issues/31 is related, but maybe not exactly

**Comment by ZiyangYan** [comment]
fixed
