### ISSUE TITLE
train_scale_factor

### ISSUE THREAD

**Issue by MiZhenxing** [cmusatyalab/mega-nerf#8]
Hi, thanks for your excellent work. I have a question about the `train_scale_factor` and `val_scale_factor`. Do the results reported in your paper all use `train_scale_factor=1` and `val_scale_factor=1`? Thank you very much.

**Comment by hturki** [comment]
The results are reported with ```train_scale_factor=1``` and ```val_scale_factor=4``` (which should be the default values set for those options)

**Comment by sumanttyagi** [comment]
@hturki  it is already set to train_scale_factor = 1 , what could be the range of this factor ? can it be float does 0.1 means 10% of data to be used for training ?
