### ISSUE TITLE
camera poses for urban3D

### ISSUE THREAD

**Issue by AIBluefisher** [cmusatyalab/mega-nerf#83]
Hi, @hturki 

I find that you already provided the camera poses for the urban3D dataset. However, the images are not provided. Because the dataset is captured with different planning methods (Oblique, Smith et al, Zhang et al, Zhou et al), it confused me a lot about the corresponding images of the provided camera poses.

**Comment by OasisArtisan** [comment]
I'm also confused about this, did you figure out which planning method from Urbanscene does Mega-Nerf use?
